import React from 'react';
import {
  LayoutDashboard,
  Users,
  User,
  Search,
  Save,
  X,
  Edit,
  Eye,
  Trash2,
  Check,
  Pause,
  Play,
  Download,
  Upload,
  Calendar,
  Clock,
  BarChart3,
  Target,
  Bot,
  Shield,
  FileText,
  FileImage,
  History,
  Bell,
  Settings,
  Copy,
  Send,
  RefreshCw,
  Menu,
  AlertTriangle,
  Info,
  Globe,
  Type,
  FileBadge,
  RotateCw,
  Printer,
  Share2,
  Mail,
  Phone,
  Lock,
  LogOut,
  Star,
  Link2,
  TestTube,
  Plug,
  Unplug,
  CheckCircle,
  XCircle,
  Filter,
  ArrowUpDown,
  Plus,
  Minus,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  BarChart,
  Activity,
  Clipboard,
  FolderOpen,
  Tag,
  MessageCircle,
  ThumbsUp,
  ThumbsDown,
  Flag,
  CalendarDays,
  MapPin,
  FileCheck,
  FileX,
  UploadCloud,
  UserCheck,
  MoreVertical,
  Columns,
  List,
  Grid,
  Table,
  PieChart,
  LineChart,
  Database,
  Building2,
  Key,
  Layers,
  Zap,
} from 'lucide-react';

const iconMap = {
  dashboard: LayoutDashboard,
  admin: Users,
  organization: Building2,
  business: Building2,
  building: Building2,
  database: Database,
  facebook: BarChart3,
  pages: FileText,
  campaign: Target,
  automation: Bot,
  analytics: BarChart3,
  reports: PieChart,
  roles: Shield,
  documents: FileText,
  audit: History,
  notifications: Bell,
  settings: Settings,
  profile: User,
  logout: LogOut,
  search: Search,
  user: User,
  email: Mail,
  phone: Phone,
  password: Lock,
  save: Save,
  cancel: X,
  edit: Edit,
  view: Eye,
  delete: Trash2,
  activate: CheckCircle,
  pause: Pause,
  play: Play,
  download: Download,
  upload: Upload,
  close: X,
  check: Check,
  warning: AlertTriangle,
  info: Info,
  success: CheckCircle,
  error: XCircle,
  calendar: Calendar,
  clock: Clock,
  globe: Globe,
  type: Type,
  assign: FileBadge,
  approve: CheckCircle,
  reject: XCircle,
  request: RotateCw,
  export: Download,
  import: Upload,
  filter: Filter,
  sort: ArrowUpDown,
  plus: Plus,
  minus: Minus,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  dot: MoreHorizontal,
  star: Star,
  file: FileText,
  image: FileImage,
  link: Link2,
  test: TestTube,
  connect: Plug,
  disconnect: Unplug,
  copy: Copy,
  send: Send,
  refresh: RefreshCw,
  menu: Menu,
  printer: Printer,
  share2: Share2,
  mail: Mail,
  phoneIcon: Phone,
  lock: Lock,
  unlock: Lock,
  shieldAlert: Shield,
  layers: Layers,
  zap: Zap,
  arrowLeft: ChevronLeft,
  arrowRight: ChevronRight,
  table: Table,
  columns: Columns,
  list: List,
  grid: Grid,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  barChart: BarChart,
  activity: Activity,
  clipboard: Clipboard,
  folderOpen: FolderOpen,
  tag: Tag,
  messageCircle: MessageCircle,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  flag: Flag,
  calendarDays: CalendarDays,
  mapPin: MapPin,
  fileText: FileText,
  fileCheck: FileCheck,
  fileX: FileX,
  uploadCloud: UploadCloud,
  userCheck: UserCheck,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  barChart2: BarChart,
  lineChart: LineChart,
  key: Key,
  fileIcon: FileText,
  downloadIcon: Download,
  uploadIcon: Upload,
  bell: Bell,
  trash: Trash2,
  checkIcon: Check,
  xCircle: XCircle,
  alertCircle: Info,
  layers2: Layers,
  pieChartIcon: PieChart,
  targetIcon: Target,
  botIcon: Bot,
  shieldIcon: Shield,
  historyIcon: History,
  usersIcon: Users,
  buildingIcon: Database,
  dashboardIcon: LayoutDashboard,
};

const Icon = ({ name, size = 18, color = 'inherit', className = '', style = {}, ...rest }) => {
  const IconComponent = iconMap[name] || MoreHorizontal;
  return (
    <IconComponent
      className={`icon icon-${name} ${className}`}
      size={size}
      color={color}
      style={style}
      {...rest}
    />
  );
};

export default Icon;
